services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'paulo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'paulo123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'paulo123'
    ports:
      - '3306:3306'
#     expose:
#       # Opens port 3306 on the container
#       - '3306'
# #       # Where our data will be persisted
#     volumes:
#       - my-db:/var/lib/mysql
# # Names our volume
# volumes:
#   my-db:
